### ISSUE TITLE
Testing of the software

### ISSUE THREAD

**Issue by Samarth0211** [CodderscluB/Image_Encryption_Decryption#5]
Points to be noted:
1. Lots of spelling mistakes.
2. In the about us section page of your software check your provided email id.
3. When we browse the image try to bring a small preview of that image on your software screen.
4. When the image encryption is done give a short message to that user about what exactly has happened.
5. When we switch to the decryption tab the key entering field should get empty.
6. Also you should provide a tab for the user to track how many and which images he/she has decrypted.

**Comment by PANDATD** [comment]
Yes, we are working on your suggestions .
